# SPDX-FileCopyrightText: 2021 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
---
root_organisation:
  name: "Aarhus"
  user_key: "root"
  municipality_code: null

facets:
  org_unit_address_type:
    AddressMailUnit:
      title: "Postadresse"
      scope: "DAR"
    AdressePostRetur:
      title: "Returadresse"
      scope: "DAR"
    AdresseHenvendelsessted:
      title: "Henvendelsessted"
      scope: "DAR"
    LocationUnit:
      title: "Lokation"
      scope: "TEXT"
    Skolekode:
      title: "Skolekode"
      scope: "TEXT"
    Formålskode:
      title: "Formålskode"
      scope: "TEXT"
    Afdelingskode:
      title: "Afdelingskode"
      scope: "TEXT"
    EmailUnit:
      title: "Email"
      scope: "EMAIL"
    PhoneUnit:
      title: "Telefon"
      scope: "PHONE"
    FaxUnit:
      title: "Fax"
      scope: "PHONE"
    EAN:
      title: "EAN-nummer"
      scope: "EAN"
    WebUnit:
      title: "Webadresse"
      scope: "WWW"
    p-nummer:
      title: "P-nummer"
      scope: "PNUMBER"
  employee_address_type:
    AdressePostEmployee:
      title: "Postadresse"
      scope: "DAR"
    PhoneEmployee:
      title: "Telefon"
      scope: "PHONE"
    LocationEmployee:
      title: "Lokation"
      scope: "TEXT"
    EmailEmployee:
      title: "Email"
      scope: "EMAIL"
  manager_address_type:
    EmailManager:
      title: "Email"
      scope: "EMAIL"
    TelefonManager:
      title: "Telefon"
      scope: "PHONE"
    AdressePostManager:
      title: "Adresse"
      scope: "DAR"
    WebManager:
      title: "Webadresse"
      scope: "TEXT"
  engagement_job_function:
    Udvikler:
      title: "Udvikler"
      scope: "TEXT"
    Specialconsultant:
      title: "Specialkonsulent"
      scope: "TEXT"
    Ergoterapeut:
      title: "Ergoterapeut"
      scope: "TEXT"
    Udviklingskonsulent:
      title: "Udviklingskonsulent"
      scope: "TEXT"
    Specialist:
      title: "Specialist"
      scope: "TEXT"
    Jurist:
      title: "Jurist"
      scope: "TEXT"
    Personalekonsulent:
      title: "Personalekonsulent"
      scope: "TEXT"
    Lønkonsulent:
      title: "Lønkonsulent"
      scope: "TEXT"
    Kontorelev:
      title: "Kontorelev"
      scope: "TEXT"
    Ressourcepædagog:
      title: "Ressourcepædagog"
      scope: "TEXT"
    Pædagoisk vejleder:
      title: "Pædagoisk vejleder"
      scope: "TEXT"
    Skolepsykolog:
      title: "Skolepsykolog"
      scope: "TEXT"
    Støttepædagog:
      title: "Støttepædagog"
      scope: "TEXT"
    Bogopsætter:
      title: "Bogopsætter"
      scope: "TEXT"
    Timelønnet lærer:
      title: "Timelønnet lærer"
      scope: "TEXT"
    Pædagogmedhjælper:
      title: "Pædagogmedhjælper"
      scope: "TEXT"
    Teknisk Servicemedarb.:
      title: "Teknisk Servicemedarb."
      scope: "TEXT"
    Lærer/Overlærer:
      title: "Lærer/Overlærer"
      scope: "TEXT"
  org_unit_type:
    Afdeling:
      title: "Afdeling"
      scope: "TEXT"
    Institutionsafsnit:
      title: "Institutionsafsnit"
      scope: "TEXT"
    Institution:
      title: "Institution"
      scope: "TEXT"
    Fagligt center:
      title: "Fagligt center"
      scope: "TEXT"
    Direktørområde:
      title: "Direktørområde"
      scope: "TEXT"
  engagement_type:
    Ansat:
      title: "Ansat"
      scope: "TEXT"
    Ekstern konsulent:
      title: "Ekstern konsulent"
      scope: "TEXT"
  association_type:
    Formand:
      title: "Formand"
      scope: "TEXT"
    Leder:
      title: "Leder"
      scope: "TEXT"
    Medarbejder:
      title: "Medarbejder"
      scope: "TEXT"
    Næstformand:
      title: "Næstformand"
      scope: "TEXT"
    Projektleder:
      title: "Projektleder"
      scope: "TEXT"
    Projektgruppemedlem:
      title: "Projektgruppemedlem"
      scope: "TEXT"
    Teammedarbejder:
      title: "Teammedarbejder"
      scope: "TEXT"
  role_type:
    Tillidsrepræsentant:
      title: "Tillidsrepræsentant"
      scope: "TEXT"
    Ergonomiambasadør:
      title: "Ergonomiambasadør"
      scope: "TEXT"
    Ansvarlig for sommerfest:
      title: "Ansvarlig for sommerfest"
      scope: "TEXT"
  leave_type:
    Barselsorlov:
      title: "Barselsorlov"
      scope: "TEXT"
    Forældreorlov:
      title: "Forældreorlov"
      scope: "TEXT"
    Orlov til pasning af syg pårørende:
      title: "Orlov til pasning af syg pårørende"
      scope: "TEXT"
  manager_type:
    Direktør:
      title: "Direktør"
      scope: "TEXT"
    Distriktsleder:
      title: "Distriktsleder"
      scope: "TEXT"
    Beredskabschef:
      title: "Beredskabschef"
      scope: "TEXT"
    Sekretariatschef:
      title: "Sekretariatschef"
      scope: "TEXT"
    Systemadministrator:
      title: "Systemadministrator"
      scope: "TEXT"
    Områdeleder:
      title: "Områdeleder"
      scope: "TEXT"
    Centerchef:
      title: "Centerchef"
      scope: "TEXT"
    Institutionsleder:
      title: "Institutionsleder"
      scope: "TEXT"
  responsibility:
    PersonaleAnsættelseAfskedigelse:
      title: "Personale: ansættelse/afskedigelse"
      scope: "TEXT"
    Beredskabsledelse:
      title: "Beredskabsledelse"
      scope: "TEXT"
    PersonaleØvrigeAdministrativeOpgaver:
      title: "Personale: øvrige administrative opgaver"
      scope: "TEXT"
    PersonaleSygefravær:
      title: "Personale: Sygefravær"
      scope: "TEXT"
    AnsvarForBygningerOgArealer:
      title: "Ansvar for bygninger og arealer"
      scope: "TEXT"
    PersonaleMUSKompetence:
      title: "Personale: MUS-kompetence"
      scope: "TEXT"
  manager_level:
    N1:
      title: "Niveau 1"
      scope: "TEXT"
    N2:
      title: "Niveau 2"
      scope: "TEXT"
    N3:
      title: "Niveau 3"
      scope: "TEXT"
    N4:
      title: "Niveau 4"
      scope: "TEXT"
  visibility:
    Intern:
      title: "Må vises internt"
      scope: "INTERNAL"
    Public:
      title: "Må vises eksternt"
      scope: "PUBLIC"
    Secret:
      title: "Hemmelig"
      scope: "SECRET"
  time_planning:
    Arbejdstidsplaner:
      title: "Arbejdstidsplaner"
      scope: "TEXT"
    DannesIkke:
      title: "Dannes ikke"
      scope: "TEXT"
    Tjenestetid:
      title: "Tjenestetid"
      scope: "TEXT"
  org_unit_level:
    N1:
      title: "N1"
      scope: "TEXT"
    N2:
      title: "N2"
      scope: "TEXT"
    N3:
      title: "N3"
      scope: "TEXT"
    N4:
      title: "N4"
      scope: "TEXT"
    N5:
      title: "N5"
      scope: "TEXT"
    N6:
      title: "N6"
      scope: "TEXT"
    N7:
      title: "N7"
      scope: "TEXT"
    N8:
      title: "N8"
      scope: "TEXT"
  primary_type:
    primary:
      title: "Primær"
      scope: "3000"
    non-primary:
      title: "Ikke-primær ansættelse"
      scope: "0"
    explicitly-primary:
      title: "Manuelt primær ansættelse"
      scope: "5000"
  kle_aspect:
    Udførende:
      title: "Udførende"
      scope: "UDFOERENDE"
    Ansvarlig:
      title: "Ansvarlig"
      scope: "ANSVARLIG"
    Indsigt:
      title: "Indsigt"
      scope: "INDSIGT"
  kle_number:
    00.01:
      title: "00.01 - Kommunens styrelse"
      scope: null
    00.01.00:
      title: "00.01.00 - Kommunens styrelse i almindelighed"
      scope: null
    00.22:
      title: "00.22 - Kommunalbestyrelsen, udvalg mv. - kommunens styrelse"
      scope: null
    00.15:
      title: "00.15 - Administrativ organisering"
      scope: null
    00.15.25:
      title: "00.15.25 - Grundlaget for effektivisering"
      scope: null
    27.03.22:
      title: "27.03.22 - Drift af dagbehandlingstilbud"
      scope: null
    29.03.06:
      title: "29.03.06 - Udstedelse af EU-sygesikringskort"
      scope: null
    00.17.15:
      title: "00.17.15 - Kommunale samarbejder"
      scope: null
    00.07.20:
      title: "00.07.20 - Videreanvendelse af den offentlige sektors informationer"
      scope: null
    28.03.20:
      title: "28.03.20 - Puljeordninger"
      scope: null

it_systems:
  OpenLDAP: "LDAP"
  Nextcloud: "NextCloud"
